# Generated by Django 4.2.8 on 2023-12-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_auto_20190904_0957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detected",
            name="photo",
            field=models.ImageField(
                default="G:/JAYASURYA/NEW OWN IN 2023/POSSIBILITIES/FACE AUTHENITCATION SYSTEM/RESOURCES/Face_recognition-master/app/facerec/detected/",
                upload_to="detected/",
            ),
        ),
    ]
