# Generated by Django 4.2.16 on 2024-11-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_employee_dominant_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedEmotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emotion', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='detected',
            name='photo',
            field=models.ImageField(upload_to='detected/'),
        ),
    ]
